model:
  name: "tfidf_logistic_regression"

  vectorizer:
    type: "TfidfVectorizer"
    params:
      max_features: 20000
      max_df: 0.95
      min_df: 1
      ngram_range: [1, 2]
      sublinear_tf: true

  classifier:
    type: "LogisticRegression"
    params:
      solver: "saga"
      multi_class: "multinomial"
      C: 2.0
      max_iter: 2000
      n_jobs: -1
      class_weight: null
